"""Helpers for turning a generated document into a downloadable report.

Kept deliberately small and beginner-readable. The report is plain Markdown
so it can be opened in any editor, pasted into Word, or shared as-is.
"""

from datetime import date


def build_markdown_report(title, body):
    """Wrap generated text in a simple Markdown report.

    Args:
        title: Name of the document (e.g. "Board briefing").
        body: The generated content.

    Returns:
        A Markdown string ready to download.
    """
    title = title or "BuildLens AI Report"
    body = body or ""
    today = date.today().isoformat()

    header = (
        f"# {title}\n\n"
        f"*Generated by BuildLens AI on {today}.*\n\n"
        "> This is an AI-generated draft based on a fixed ESG knowledge base. "
        "Please review for accuracy before sharing or making decisions.\n\n"
        "---\n\n"
    )

    footer = (
        "\n\n---\n\n"
        "_BuildLens AI - turn construction ESG documents into source-backed decisions._\n"
    )

    return header + body + footer
